### ISSUE TITLE
Tạo mới Hotel Thiếu description

### ISSUE THREAD

**Issue by haith2207** [lilotech-2019/home-stay#13]
**Describe the bug**

**To Reproduce**
1. Go to '/Portal/Hotel/Create'

**Expected behavior**
Hiện khung description có apply CKEditor

**Screenshots**

**Comment by ghost** [comment]
![ảnh](https://user-images.githubusercontent.com/42989567/57578294-93d9c000-74b3-11e9-8931-12b547a2dee8.png)

Create hotel vẫn có description và đã được apply CKeditor

**Comment by haith2207** [comment]
Cái này là bug log demo.
