### ISSUE TITLE
chỉ cho load bài blog nếu category là tin-tức thôi

### ISSUE THREAD

**Issue by huongmainguyen** [lilotech-2019/home-stay#15]

**Comment by ghost** [comment]
không hiểu lắm ? vì thấy load bài vẫn load đầy đủ mà ?
![ảnh](https://user-images.githubusercontent.com/42989567/57578562-07320080-74b9-11e9-988b-4a25c64ae6c1.png)
![ảnh](https://user-images.githubusercontent.com/42989567/57578563-0ac58780-74b9-11e9-83e3-a124374c8a1f.png)

**Comment by haith2207** [comment]
Cái này là bên phía mai đang dùng ké service của admin. 
Ở đây có những cách giải quyết như sau cho mai chon.
1. Ở controller load news phía end user em thêm đk .where(slug == tin-tuc)
2. Ở phía admin set status = true vs mục nào là tin tức. Qua bên end user load theo đk stus tru.
3. Mai viết 1 service cho phía end user. Hoặc nhờ thành viết cho 1 bé.

**Comment by haith2207** [comment]
Cái này không phải là bug nhé.
