### ISSUE TITLE
Thanh toán không được 

### ISSUE THREAD

**Issue by chitrung252** [lilotech-2019/home-stay#20]
![a22](https://user-images.githubusercontent.com/34767666/57585451-90c1ec80-7512-11e9-83c1-268f1f919510.PNG)
![a23](https://user-images.githubusercontent.com/34767666/57585452-915a8300-7512-11e9-95cd-177c93898e94.PNG)
![a21](https://user-images.githubusercontent.com/34767666/57585453-915a8300-7512-11e9-8ff6-25a7e93140b9.PNG)
Quản lí booking -> nhưng user đã thanh toán -> click thanh -> kéo xuống phần review -> click thanh toán thì bị lỗi

**Comment by ghost** [comment]
Đã fix 

p/s: Đã cập nhập lại luồng đi của roomOrder
