### ISSUE TITLE
Chỉnh sửa lại Icon cho Menu

### ISSUE THREAD

**Issue by haith2207** [lilotech-2019/home-stay#24]
Tham khảo file _HotelCategorySubMenu.cshtml. 

![2019-05-18_18-15-29](https://user-images.githubusercontent.com/5533873/57968790-38b73a00-7999-11e9-96b7-8bcd7fd0ea57.png)

**Comment by ghost** [comment]
Đã fix
![image](https://user-images.githubusercontent.com/42989567/57979844-14b53080-7a4d-11e9-8dcb-0523088ac3af.png)
