### ISSUE TITLE
Chỉnh Sửa giao diện trang Hotel/Index

### ISSUE THREAD

**Issue by haith2207** [lilotech-2019/home-stay#25]
[https://localhost:44379/portal/hotels](url)
Chỉnh sửa lại icon, gắn link cho các chức năng cho đúng
![2019-05-18_18-15-29](https://user-images.githubusercontent.com/5533873/57971173-ade43880-79b4-11e9-9548-5834c195e73c.png)

**Comment by ghost** [comment]
đã tạo menu động
