### ISSUE TITLE
TrangPortal/Hotel/Index

### ISSUE THREAD

**Issue by haith2207** [lilotech-2019/home-stay#26]
![2019-05-18_18-15-29](https://user-images.githubusercontent.com/5533873/57972773-3e2c7880-79c9-11e9-8ecf-cbb05683f10f.png)
[https://localhost:44379/portal/hotels#](url)

TODO

- Thêm Phân Trang
- Thêm Search Name
- Sửa Icon hiển thị ở menu quản lý trang lại cho phù hợp (menu nằm ngang), Bỏ nút tất cả đi vì thấy ko cần thiết. 
- Cố định chiều cao của  khung hiển thị (chiều cao border) set height,  giới hạn số từ cho description

**Comment by ghost** [comment]
Đã fix
